os: osx
osx_image: xcode8.2
language: node_js
before_install:
  - brew update
  - brew install gnu-tar graphicsmagick rpm
node_js:
  - "6"
script:
  - npm run lint
before_deploy:
  - npm run build-mac
  - npm run build-linux
  - export VERSION=$(echo $TRAVIS_TAG | tr -d "v")
deploy:
  - provider: releases
    api_key: $GITHUB_ACCESS_TOKEN
    file:
      - "releases/mac/ndm-$(echo $VERSION).dmg"
      - "releases/ndm_$(echo $VERSION)_amd64.deb"
      - "releases/ndm-$(echo $VERSION).rpm"
      - "releases/ndm-$(echo $VERSION).zip"
    skip_cleanup: true
    on:
      tags: true
  - provider: packagecloud
    repository: "ndm"
    username: "wouldgo"
    token: $PACKAGECLOUD_TOKEN
    dist: "ubuntu/trusty"
    package_glob: releases/**/*.deb
    skip_cleanup: true
    on:
      tags: true
