os: osx
osx_image: xcode8.2
language: node_js
before_install:
  - brew update
  - brew install gnu-tar graphicsmagick rpm
  - gem install package_cloud
node_js:
  - "6"
script: "echo build done"
before_deploy:
  - npm run lint
  - npm run build-mac
  - npm run build-linux
  - export VERSION=$(echo $TRAVIS_TAG | tr -d "v")
deploy:
  - provider: releases
    api_key: $GITHUB_ACCESS_TOKEN
    file:
      - "releases/mac/ndm-$(echo $VERSION).dmg"
      - "releases/ndm_$(echo $VERSION)_amd64.deb"
      - "releases/ndm-$(echo $VERSION).rpm"
      - "releases/ndm-$(echo $VERSION).zip"
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script:
      - package_cloud push wouldgo/ndm/debian/buster releases/ndm_$(echo $VERSION)_amd64.deb
      - package_cloud push wouldgo/ndm/elementaryos/freya releases/ndm_$(echo $VERSION)_amd64.deb
      - package_cloud push wouldgo/ndm/ubuntu/trusty releases/ndm_$(echo $VERSION)_amd64.deb
      - package_cloud push wouldgo/ndm/ubuntu/utopic releases/ndm_$(echo $VERSION)_amd64.deb
      - package_cloud push wouldgo/ndm/ubuntu/vivid releases/ndm_$(echo $VERSION)_amd64.deb
      - package_cloud push wouldgo/ndm/ubuntu/wily releases/ndm_$(echo $VERSION)_amd64.deb
      - package_cloud push wouldgo/ndm/ubuntu/xenial releases/ndm_$(echo $VERSION)_amd64.deb
      - package_cloud push wouldgo/ndm/ubuntu/yakkety releases/ndm_$(echo $VERSION)_amd64.deb
      - package_cloud push wouldgo/ndm/linuxmint/serena releases/ndm_$(echo $VERSION)_amd64.deb
      - package_cloud push wouldgo/ndm/opensuse/42.1 releases/ndm-$(echo $VERSION).rpm
      - package_cloud push wouldgo/ndm/fedora/25 releases/ndm-$(echo $VERSION).rpm
      - package_cloud push wouldgo/ndm/el/7 releases/ndm-$(echo $VERSION).rpm
    on:
      tags: true
