os: osx
osx_image: xcode8.2
language: node_js
before_install:
  - brew update
  - brew install gnu-tar graphicsmagick rpm
node_js:
  - "6"
script: "echo build done"
before_deploy:
  - npm run build
  - export VERSION=$(echo $TRAVIS_TAG | tr -d "v")
deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  file:
    - "releases/mac/ndm-$(echo $VERSION).dmg"
    - "releases/ndm_$(echo $VERSION)_amd64.deb"
    - "releases/ndm-$(echo $VERSION).rpm"
    - "releases/ndm-$(echo $VERSION).zip"
    - "ndm Setup $(echo $VERSION).exe"
  skip_cleanup: true
  on:
    tags: true
