os: osx
osx_image: xcode8.2
language: node_js
before_install:
  - brew update
  - brew install gnu-tar graphicsmagick rpm
node_js:
  - "6"
script: "echo build done"
before_deploy: npm run build-mac && npm run build-linux
deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  file:
    - "releases/mac/ndm_$(echo $TRAVIS_TAG).dmg"
    - "releases/ndm_$(echo $TRAVIS_TAG)_amd64.deb"
    - "releases/ndm-$(echo $TRAVIS_TAG)-x86_64.AppImage"
    - "releases/ndm-$(echo $TRAVIS_TAG).rpm"
  skip_cleanup: true
  on:
    tags: true
