os: osx
osx_image: xcode8.2
language: node_js
before_install:
  - brew update
  - brew install gnu-tar graphicsmagick rpm
node_js:
  - "6"
script: "echo build done && pwd"
before_deploy:
  - npm run build-mac
  - export VERSION=$(echo $TRAVIS_TAG | tr -d "v")
deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  file:
    - "/releases/mac/ndm-$(echo $VERSION).dmg"
  skip_cleanup: true
  on:
    tags: true
