
os: Visual Studio 2015

platform:
  - x86

install:
  - npm install && npm run lint && npm run build-win

build: off
test: off
 
artifacts:
  - path: 'releases\*.exe'
  
branches:
  only:
    - master

deploy:
  provider: GitHub
  auth_token: 
    secure: vpS3QtQEPy/DC+8dYXY5VRd2ZSOCLJRx1/cYZSrs6qAWjokQEhgD3RTxrgbFcRQK   
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true    
