
os: Visual Studio 2015

platform:
  - x86

install:
  - npm install && npm run lint && npm run build-win

build: off
test: off

branches:
  only:
  - master

artifacts:
- path: releases\*.exe

deploy:
- provider: GitHub
  auth_token:
    secure: i18IKlzw8mJ/ypnDh236MBrTPYMfJobcubpxCOIBDMI+fwklx8CPy+Ie9JE/BrohRNzJgSVZmd4D2Y1R3glmZsH/kq17KusYRbYW7Xao59M=
  draft: true
  prerelease: true
  force_update: true
  on:
    branch: master
