environment:
  nodejs_version: '6'
  
platform:
  - x86

install:
  - ps: Install-Product node $env:nodejs_version
  - echo 'NODE_VERSION' && node -v
  - echo 'NPM_VERSION' && npm -v
  - npm install
  - npm prune
  
build: off
test: off

artifacts:
  path: releases\*.exe

deploy:
- provider: GitHub
  auth_token:
    secure: tsButLvk52+UaRqT1htE6Lw8Txzy5fq3pvK21gbLd9NNbYBArjt1GgonfVDccyKr
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
