
os: Visual Studio 2015

platform:
  - x86

install:
  - npm install && npm run lint && npm run build-win

build: off
test: off

branches:
  only:
  - master

deploy:
- provider: GitHub
  artifact: releases\*.exe
  auth_token:
    secure: i18IKlzw8mJ/ypnDh236MBrTPYMfJobcubpxCOIBDMI+fwklx8CPy+Ie9JE/BrohRNzJgSVZmd4D2Y1R3glmZsH/kq17KusYRbYW7Xao59M=
    branch: master               # release from master branch only
    appveyor_repo_tag: true       # deploy on tag push only
