
os: Visual Studio 2015

platform:
  - x86

install:
  - npm install && npm run lint && npm run build-win

artifacts:
  - path: 'releases\*.exe'
  
branches:
  only:
    - master

# disable build and test pahses
build: off
test: off
