environment:
  nodejs_version: '6'
  
platform:
  - x86

install:
  #- ps: Install-Product node $env:nodejs_version
  #- echo 'NODE_VERSION' && node -v
  #- echo 'NPM_VERSION' && npm -v
  - npm install
  - npm prune
  - npm run build-win
 
test: off

artifacts:
  path: releases\*.exe
  
before_deploy:
 - set APP_VERSION=$(node -p -e "require('./package.json').version") #export package.json app version
 - set APP_NAME=$(node -p -e "require('./package.json').name") #export package.json app name
 - rename "releases\%APP_NAME% Setup %APP_VERSION%.exe" releases\%APP_NAME%-%VERSION%.exe

deploy:
- provider: GitHub
  auth_token:
    secure: tsButLvk52+UaRqT1htE6Lw8Txzy5fq3pvK21gbLd9NNbYBArjt1GgonfVDccyKr
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
