os: Visual Studio 2015

environment:
  nodejs_version: "6"

platform:
  - x86

install:
  - npm install && npm run lint && npm run build-win

build: off
test: off

artifacts:
  path: releases\*.exe

deploy:
- provider: GitHub
  auth_token:
    secure: tsButLvk52+UaRqT1htE6Lw8Txzy5fq3pvK21gbLd9NNbYBArjt1GgonfVDccyKr
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
